//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public bool IsLikeWater { get; set; }
        public bool IsLikeShadow { get; set; }
        public bool IsLikeSunny { get; set; }
        public bool IsLikeDry { get; set; }
        public int RecommendSunnyHour { get; set; }
        public int RecommendWater { get; set; }
        public int RecommendFertilizer { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
